Ispit.Todo/Models/Todolist.cs
using Ispit.Todo.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ispit.Todo.Models
{
    public class Todolist
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Naziv grupe zadataka")]
        public string Title { get; set; }

        [Display(Name = "Opis grupe zadataka")]
        public string Description { get; set; }

        [ForeignKey("UserId")]
        public ApplicationUser? User { get; set; }
        public string? UserId { get; set; }
        [NotMapped]
        public ICollection<TaskTodo>? Tasks { get; set; }



    }

}

Ispit.Todo/Controllers/TodolistController.cs
using Ispit.Todo.Data;
using Ispit.Todo.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ispit.Todo.Controllers
{
    public class TodolistController : Controller
    {
        private readonly ApplicationDbContext _context;
 
        public TodolistController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Todolist
        public ActionResult Index(int? todoId)
        {

            List<Todolist> tasks = (todoId != null) ?

               _context.Todolist.Where(p => _context.Task.Where(pc => pc.TodolistId == todoId).Select(
                           pc => pc.TodolistId
                       ).ToList().Contains(
                           p.ID
                       )
               ).ToList() :
               _context.Todolist.ToList();
            ViewBag.Task = _context.Task.ToList();
            if (todoId != null)
            {
                ViewBag.Task = _context.Task.Where(s => s.TodolistId == todoId).ToList();
            }
           
            ViewBag.Todolists = _context.Todolist.ToList();



            return View(tasks);
        }

        // GET: Todolist/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Todolist/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Todolist/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Todolist todolist)
        {
            try
            {
                _context.Todolist.Add(todolist);
                _context.SaveChanges();
                var taskIsEmpty = _context.Task.Count();
                if (taskIsEmpty == 0)
                {
                    return RedirectToAction("Create", "Task", _context.Task.ToList());
                }
                else
                {
                    return RedirectToAction("Index");
                }
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Todolist/Edit/5
        public ActionResult Edit(int id)
        {
            var todolist = _context.Todolist.FirstOrDefault(s => s.ID == id);

            if (todolist == null)
            {
                return RedirectToAction("Index");
            }

            return View(todolist);
        }

        // POST: Todolist/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Todolist todolist)
        {
            try
            {
                _context.Todolist.Update(todolist);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
       
    }
}

Ispit.Todo/Views/Todolist/Create.cshtml
@model Ispit.Todo.Models.Todolist

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Todolist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
           
            <div class="form-group mt-1">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ispit.Todo/Views/Todolist/Index.cshtml
@model List<Todolist>
<h1>Moji zadaci</h1>


@if(ViewBag.Todolists.Count == 0)
{
    <h3>Nemaš dodanih zadataka</h3>
    <hr />
<a class="btn btn-primary" asp-area="" asp-controller="Todolist" asp-action="Create">Dodaj zadatak</a>

}
else
{
    <div class="row mb-5">
        <div class="col-6">

        <form method="GET" asp-area="" asp-controller="Todolist" asp-action="Index">

            <div class="input-group mb-3">
                    
                <select class="form-select" id="floatingSelect" name="todoId">
                    <option selected value="">All</option>
                    @foreach(var task in ViewBag.Todolists)
                    {
                    <option value="@task.ID">@task.Title</option>
                    }
                </select>
                   
                <div class="input-group-append">
                    <button type="submit" class="btn btn-info">Filter</button>
                </div>
            </div>
           
        </form>
        
    </div>
    <div class="col-6 text-end">
        <a class="btn btn-primary" asp-controller="Todolist" asp-action="Create">Dodaj grupu</a>
        <a class="btn btn-primary" asp-controller="Task" asp-action="Create">Dodaj zadatak</a>
    </div>
</div>
    @if (ViewBag.Task != null)
    {
        <table class="table table-hover">
      
        <tbody>
            @foreach(var task in @ViewBag.Task)
            {
                if (task.Status == false)
                {
                    <tr>
                        <td>
                            @using (Html.BeginForm("ChangeStatusTask", "Task", FormMethod.Post))
                            {
                                <input type="hidden" name="id" value="@task.Id"/>
                                <button type="submit" class="btn btn-info"><i class="far fa-square"></i></button>
                            }

                        </td>
                        <td>@task.TitleTask</td>
                        <td>@task.CreatedDate</td>
                        <td>Edit | Delete</td>
               
                    </tr>
                }
            }
       
        </tbody>
    </table>
    }
    

    
}